---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Blantyre
    volumes:
      - ./config/jellyfin:/config
      - /mnt/media/tv:/tv
      - /mnt/media/movies:/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Blantyre
    volumes:
      - ./config/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      media_nw:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Blantyre
    volumes:
      - ./config/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      media_nw:
        ipv4_address: 172.20.0.20
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Blantyre
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/media/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      media_nw:
        ipv4_address: 172.20.0.30
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Blantyre
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/downloads:/downloads
      - ./config/jackett:/config
    ports:
      - 9117:9117
    networks:
      media_nw:
        ipv4_address: 172.20.0.40
    restart: unless-stopped

  filebrowser:
    image: hurlenko/filebrowser
    container_name: file
    ports:
      - 443:8080
    volumes:
      - /mnt:/data
      - ./config/file:/config
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=1000
      - PGID=1000
    networks:
      media_nw:
        ipv4_address: 172.20.0.45
    restart: unless-stopped

networks:
  media_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
